include: package:flutter_lints/flutter.yaml

# All rules found here: https://dart-lang.github.io/linter/lints/

linter:
  rules:
    - avoid_dynamic_calls
    - directives_ordering
    - always_put_required_named_parameters_first
    - eol_at_end_of_file
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - use_super_parameters
    - sort_pub_dependencies
    - omit_local_variable_types
    - prefer_relative_imports
