name: flutter_popup_card
description: A Flutter plugin to create a card or custom widget that can popup overtop of your main app.
version: 0.0.2
homepage: https://github.com/jacksoncurrie/flutter_popup_card
repository: https://github.com/jacksoncurrie/flutter_popup_card
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/package_info_plus

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
